[
    {"nombre": "Juan", "edad": 25, "ciudad": "Madrid", "profesion": "Ingeniero"},
    {"nombre": "Ana", "edad": 30, "ciudad": "Cádiz", "profesion": "Médico"},
    {"nombre": "Pedro", "edad": 25, "ciudad": "Madrid", "profesion": "Profesor"},
    {"nombre": "Luis", "edad": 30, "ciudad": "Valencia", "profesion": "Abogado"},
    {"nombre": "Carmen", "edad": 40, "ciudad": "Madrid", "profesion": "Médico"},
    {"nombre": "Jose", "edad": 40, "ciudad": "Bilbao", "profesion": "Ingeniero"},
    {"nombre": "Maria", "edad": 22, "ciudad": "Sevilla", "profesion": "Ingeniero"},
    {"nombre": "Pablo", "edad": 35, "ciudad": "Bilbao", "profesion": "Profesor"},
    {"nombre": "Eva", "edad": 28, "ciudad": "Barcelona", "profesion": "Médico"},
    {"nombre": "Raul", "edad": 22, "ciudad": "Valencia", "profesion": "Profesor"},
    {"nombre": "Laura", "edad": 30, "ciudad": "Sevilla", "profesion": "Ingeniero"},
    {"nombre": "Elena", "edad": 40, "ciudad": "Madrid", "profesion": "Abogado"},
    {"nombre": "Alberto", "edad": 33, "ciudad": "Bilbao", "profesion": "Profesor"},
    {"nombre": "Sara", "edad": 28, "ciudad": "Cádiz", "profesion": "Ingeniero"},
    {"nombre": "Victor", "edad": 35, "ciudad": "Sevilla", "profesion": "Profesor"},
    {"nombre": "Julia", "edad": 30, "ciudad": "Valencia", "profesion": "Ingeniero"},
    {"nombre": "David", "edad": 40, "ciudad": "Madrid", "profesion": "Profesor"},
    {"nombre": "Lucia", "edad": 22, "ciudad": "Bilbao", "profesion": "Ingeniero"},
    {"nombre": "Irene", "edad": 35, "ciudad": "Sevilla", "profesion": "Médico"},
    {"nombre": "Juani", "edad": 33, "ciudad": "Cádiz", "profesion": "Estudiante"},
    {"nombre": "Manuel", "edad": 28, "ciudad": "Cádiz", "profesion": "Profesor"}
]
