name: Run Pytest with Verbose Output

on:
  push:
    branches:
      - main  # Ejecutar las pruebas cuando se haga un push a la rama main
  pull_request:
    branches:
      - main  # Ejecutar las pruebas en cada pull request hacia la rama main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Especifica la versión de Python, por ejemplo '3.9' o '3.x' para la más reciente

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Instalar pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Instalar dependencias si hay un requirements.txt

    - name: Run Pytest with Verbose
      run: |
        pytest -v tests  # Ejecutar pytest en modo verbose sobre la carpeta tests
