# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: 'R Z O'
site_url: 'https://revilofe.github.io'
repo_url: 'https://github.com/revilofe/revilofe.github.io'
repo_name: 'GitHub'
edit_uri: edit/main/docs/
site_author: 'Eduardo Fdez'



nav:
  - 'Principal': 'index.md'
  - 'Programación':
    - 'section1/index.md'
    - 'U1: Introducción al desarrollo de software':
        - 'section1/u01/index.md'
        - '1.1.-Un programa': 'section1/u01/teoria/PROG-U1.1.-UnProgramaInformatico.md'
        - '* Práctica 1.1: Instala python': 'section1/u01/practica/PROG-U1.-Practica001.md'
        - '1.2.-Practica con un lenguaje': 'section1/u01/teoria/PROG-U1.2.-PracticaConUnLenguajes.md'
        - '1.3.-Tipos de datos': 'section1/u01/teoria/PROG-U1.3.-TiposDeDatos.md'
        - '* Práctica 1.2: Primeros programas': 'section1/u01/practica/PROG-U1.-Practica002.md'
    - 'U2: Sentencias condicionales y repetitivas':
        - 'section1/u02/index.md'
        - '2.1.-Condicionales': 'section1/u02/teoria/PROG-U2.1.-Condicionales.md'
        - '* Práctica 2.1: Sentencias condicionales': 'section1/u02/practica/PROG-U2.-Practica001.md'
        - '2.2.-Iterativas y saltos': 'section1/u02/teoria/PROG-U2.2.-Iterativas.md'
        - '* Práctica 2.2: Sentencias iterativas y saltos': 'section1/u02/practica/PROG-U2.-Practica002.md'
        - '2.3.-Captura de excepciones': 'section1/u02/teoria/PROG-U2.3.-Excepciones.md'
        - '* Práctica 2.3: Capturas de excepciones': 'section1/u02/practica/PROG-U2.-Practica003.md'
        - '2.4.-Depurar programas': 'section1/u02/teoria/PROG-U2.4.-Depurar.md'
        - '* Práctica 2.4: Depurar programas': 'section1/u02/practica/PROG-U2.-Practica004.md'
        - '2.5.-Documentar el código': 'section1/u02/teoria/PROG-U2.5.-Documentar.md'
        - '* Práctica 2.5: Proyecto': 'https://classroom.github.com/a/1NxxJ6nu'

  - 'Entornos de desarrollo':
    - 'section3/index.md'
    - 'U1: Introducción al desarrollo de software':
        - 'section3/u01/index.md'
        - '1.1.-Software y PC': 'section3/u01/teoria/EDES-U1.1.-Software-PC.md'
        - '1.2.-Lenguajes de programación': 'section3/u01/teoria/EDES-U1.2.-Lenguajes.md'
        - '1.3.-Herramientas y funcionalidades': 'section3/u01/teoria/EDES-U1.3.-FuncionalidadesHerramientas.md'
        - '1.4.-Traductores': 'section3/u01/teoria/EDES-U1.4.-Traductores.md'
        - 'Práctica 1: Lenguajes de programación': 'section3/u01/practica/EDES-U1.-Practica001.md'
        - 'Práctica 2: Herramientas para generar programa': 'section3/u01/practica/EDES-U1.-Practica002.md'
  - 'Incidentes de seguridad':
    - 'section2/index.md'
    - 'U0: Nos conocemos': 'section2/u00/recursos/IS-U0.-DinamicaPresentacion.md'
    - 'U1: Principios generales y planes de seguridad':
      - 'section2/u01/index.md'
      - '1.1.-PrincipiosGenerales': 'section2/u01/teoria/IS-U1.1.1.-PrincipiosGenerales.md'
    - 'Unidad 2': 'section2/page-2.md'
    - 'Unidad 3': 'section2/page-3.md'
    - 'Unidad 4': 'section2/page-4.md'
    - 'Unidad 5': 'section2/page-5.md'
    - 'Unidad 6': 'section2/page-6.md'
    - 'Unidad 7': 'section2/page-7.md'
    - 'Unidad 8': 'section2/page-8.md'
  - 'Blog': 'blog.md'
  - 'Tags': 'tags.md'
  - 'Acerca de': 'about.md'


#extra_css:
#  - stylesheets/extra.css # The width of the content area is set so the length of each line doesn't exceed 80-100 characters, depending on the width of the characters. While this is a reasonable default, as longer lines tend to be harder to read, it may be desirable to increase the overall width of the content area, or even make it stretch to the entire available space.

theme:
  name: material
  language: es
  logo: assets/ms-icon-144x144.png
  favicon: assets/favicon-96x96.png
  font:
    text: Roboto
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
  features:
    - navigation.tabs # When tabs are enabled, top-level sections are rendered in a menu layer below the header for viewports above 1220px, but remain as-is on mobile.1 
    - navigation.tabs.sticky # When sticky tabs are enabled, navigation tabs will lock below the header and always remain visible when scrolling down.
    - navigation.sections # When sections are enabled, top-level sections are rendered as groups in the sidebar for viewports above 1220px, bu
#    - navigation.instant # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page. navigation.instant feature cannot be enabled if blog paging is on
    - navigation.tracking # When anchor tracking is enabled, the URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - navigation.expand # When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually.
    - navigation.indexes # When section index pages are enabled, documents can be directly attached to sections, which is particularly useful for providing overview pages. 
    - navigation.top # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again
    - content.tooltips #Tooltips
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate #Code annotations offer a comfortable and friendly way to attach arbitrary content to specific sections of code blocks by adding numeric markers in block and inline comments in the language of the code block. Add the following to mkdocs.yml to enable them globally:
  icon:
    tag:
      etiqueta: octicons/tag-24

markdown_extensions:
  - toc:
      permalink: true
      title: Contenidos
  - tables
  - meta
  - abbr #Tooltips
  - attr_list #Tooltips & This configuration adds the ability to align images, add captions to images (rendering them as figures), and mark large images for lazy-loading.
  - md_in_html # https://squidfunk.github.io/mkdocs-material/reference/images/
  - admonition
  - def_list
  - footnotes
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets: #Tooltips https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-tooltips
      auto_append: 
        - includes/abbreviations.md

# Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true #The Tabbed extension allows the usage of content tabs, a simple way to group related content and code blocks under accessible tabs.
  - pymdownx.tasklist:
      custom_checkbox: true #The Tasklist extension allows for the usage of GitHub Flavored Markdown inspired task lists, following the same syntactical conventions.


plugins:
  - tags:
      tags_file: 'tags.md'
  - search:
      lang: es
  - blogging: # https://liang2kl.codes/mkdocs-blogging-plugin/
#      locale: es-ES
      # {{ blog_content }}
      dirs: # The directories to be included, dentro de docs
        - blog
      size: 5
      paging: true        # Paging
      show_total: true    # 'total pages' label
#      full_content: true  # Use the full content for blog description
      theme:              # Use a predefined theme
        name: card
      features:
        tags: {}
#  - social:
#      cards_color:
#        fill: "#0FF1CE" 
#        text: "#FFFFFF"
#      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
#      cards_dir: assets/images/social
      
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/revilofe
      #name: Twitter
    - icon: fontawesome/solid/envelope
      link: mailto:<efernandez@iesrafaelalberti.es>
      name: e-mail
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/efoliver
      #name: LinkedIn
#  social:
#    - type: 'github'
#      link: 'https://github.com/revilofe'
#    - type: 'twitter'
#      link: 'https://twitter.com/revilofe'
  version:
    provider: mike
  tags:
    etiqueta: etiqueta
  search:
    language: "es"
  analytics: #https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics
    provider: google
    property: G-GT5TGHD4YQ
    feedback:
      title: ¿Te ha sido útíl la página?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Me ha sido de utilidad.
          data: 1
          note: >-
            Gracias por tu feedback!
        - icon: material/emoticon-sad-outline
          name: La página podría mejorar.
          data: 0
          note: >- 
            Gracias por tu feedback! Ayudame a mejorarla usando este formulario. <a href="https://forms.gle/bBtzHfjb41unBb5o9" target=_blank>feedback form</a>.
  generator: false


copyright: 2021-2022 Eduardo Fernández <a href="https://twitter.com/revilofe" target=_blank>@revilofe</a> - Licencia CC BY-NC-SA
